image:
  repository: kong-with-plugin-image
  tag: "latest"

env:
  database: postgres
  pluginserver_names: go-hello
  pluginserver_go_hello_socket: /usr/local/kong/go-hello.socket
  pluginserver_go_hello_start_cmd: /usr/local/bin/go-hello
  pluginserver_go_hello_query_cmd: /usr/local/bin/go-hello -dump
  plugins: bundled,go-hello

admin:
  enabled: true
  http:
    enabled: true
    servicePort: 8001
    containerPort: 8001
  tls:
    parameters: []

proxy:
  servicePort: 8000
  containerPort: 8000

postgresql:
  enabled: true
  auth:
    username: kong
    database: kong
    password: kong
    postgresPassword: kong

ingressController:
  enabled: true
  installCRDs: false

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
