apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: hello-world
spec:
  ports:
    - name: "8090"
      port: 8090
      targetPort: 8090
  selector:
    app: hello-world
  type: LoadBalancer
status:
  loadBalancer: {}
